spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail@here.com
    password: yourpasswordhere
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
